### ISSUE TITLE
initialSizes has no effect

### ISSUE THREAD

**Issue by hkjasf687261gh** [b-zurg/react-collapse-pane#37] opened 2020-07-25 00:52 UTC
Version 1.4.2

Hi mate, im having issues with the `initialSizes` prop, which does not seem to be responding to any values. The panes always render with a 1,1,1 ratio (even if the initialSizes prop has a [1,2,1] ratio)

I tried downgrading a few versions but had the same issue,
I tried upgrading to v2.0.0, but in this version I can't even move the bars.

Do you have any any idea what might be causing it?

```javascript
const AppContent: React.FC = () => {
  const dispatch = useDispatch();
  const { theme, windowPaneLocations } = useSelector((state: StateInterface) => state.settings);
  const currentTheme = getTheme(theme);

  const updateWindowPaneLocations = useCallback(
    (value: number[]) => {
      dispatch(settingsActions.update({ windowPaneLocations: value }));
    },
    [dispatch],
  );

  return (
    <DndProvider backend={HTML5Backend}>
      <ThemeProvider theme={currentTheme}>
        <SplitPane
          split="vertical"
          initialSizes={windowPaneLocations}
          minSizes={250}
          hooks={{ onSaveSizes: (sizes) => updateWindowPaneLocations(sizes) }}
        >
          <CollectionView />
          <FolderView />
          <NoteView />
        </SplitPane>
      </ThemeProvider>
    </DndProvider>
  );
};

```

**Comment by b-zurg** [comment] 2020-07-25 09:16
Interesting...  This is not something I've come across before.   

I made a code sandbox to try to reproduce it as much as possible but it seems to work fine - https://codesandbox.io/s/react-collapse-pane37-wzgt3

In your environment, are you able to render something really barebones like the code sandbox and does it work in that case?  

Otherwise the best bet for figuring this out is to have it reproducable in a sandbox environment.   What happens  if you don't include `minSizes` ?

**Comment by hkjasf687261gh** [comment] 2020-07-26 04:08
I've isolated what component is causing the problem, [`<IonContent>` (link to docs)](https://ionicframework.com/docs/api/content). Which is a layout component used to help scrollable area content (probably the cause) with the Ionic Framework (which allows you to build mobile/desktop apps with React).

https://ionicframework.com/docs/api/content

i've uploaded example project here, https://github.com/hkjasf687261gh/split-pane-ionic-issue/tree/master/src/pages
You can click between the splitpane being broken and working, the only difference is the broken one is wrapped in `IonContent` and the fixed one is not.

to get it to run you'd need to setup ionic sorry, then yarn and serve.

```
npm install -g @ionic/cli
yarn
ionic serve
```

**Comment by b-zurg** [comment] 2020-07-27 18:44
Thanks!!  This is very helpful.   I'll take a look into it soon.

**Comment by b-zurg** [comment] 2020-07-27 19:15
I'm going to focus on fixing this for V2.  The root cause of it seems to be an interference with `getBoundingClientRect()` which is used in the `useGetCurrentPaneSizes` hook.  This is a key part of the library as it's how it figures out what the flex-basis sizes should be.

Here's an example of what's returned when wrapped with ionic
```js
bottom: 0
height: 0
left: 0
right: 0
top: 0
width: 0
x: 0
y: 0
```
And when not: 
```js
bottom: 1076.666748046875
height: 1076.666748046875
left: 891.4583740234375
right: 1336.68408203125
top: 0
width: 445.2257080078125
x: 891.4583740234375
y: 0
```

I think there might also be some interference with the window event listener... but from some initial testing I don't think that's the problem.  I think the differences between v1.x and v2.x might shed some light on the root cause.

**Comment by JoshRosenstein** [comment] 2020-10-30 22:19
@hkjasf687261gh  @b-zurg 
Stumbled upon this issue and opened up the sandbox and found that `ion-content` is not the underlying issue. For example switch your Redirect Route to 
```jsx
<Route exact path="/" render={() => <Redirect to="/fix" />} />
```
This will show that both pages are broken. 
This is related to a deeper Ionic issue which you can find here: https://github.com/ionic-team/ionic-framework/issues/19770

**Comment by b-zurg** [comment] 2020-11-26 18:05
@JoshRosenstein  nice find!  I'm not sure what's the best approach to this though as I'm hesitant to add a polyfill to the dependencies.  One possibility would be to abstract out the size calculation hook so that it can be passed in as an optional parameter. That's the only clean solution I can think of to this issue.  Thoughts?

**Comment by JoshRosenstein** [comment] 2020-11-28 01:04
@b-zurg , another option is you can just leave it up to the user to provide the polyfill if need be. Kinda like how [react-use](https://github.com/streamich/react-use) has implemented [useMeasure](https://github.com/streamich/react-use/blob/master/src/useMeasure.ts) and a note about it in its  [Docs](https://github.com/streamich/react-use/blob/master/docs/useMeasure.md).

**Comment by b-zurg** [comment] 2021-05-13 09:02
Yeah I think that is probably the easiest option.  I have some ideas for a new major release as well which will simplify several aspects of this approach, however I think it will still rely upon `getBoundingClientRect` so a polyfill sounds like a good approach.  

I'll make another issue to add some of these notes to the docs. There was also another issue about AbortController for IE support that I think would best be solved by a polyfill.  

I will create a new issue for adding these to the docs and close this one.

If that is not satisfactory please add a comment.

**Closed by b-zurg** 2021-05-13 09:02 UTC
Labels: fix
